### ISSUE TITLE
Python 3.5 "SyntaxError: invalid syntax" due to f-strings

### ISSUE THREAD

**Issue by smelton-snowfall** [CyberSource/cybersource-rest-client-python#39]
Traceback (most recent call last):
...
File "../virtualenv/lib64/python3.5/site-packages/CyberSource/apis/capture_api.py", line 143
    return self.api_client.call_api(f'/pts/v2/payments/{id}/captures',
                                                                    ^
SyntaxError: invalid syntax
>>>

Receiving this error using Python 3.5. Requirements state Python 3.4+ is supported, however, code uses f-strings which are only supported in 3.6.

**Comment by snavinch** [comment]
Thank you for bringing this to our attention, We have corrected the version requirements in the read me.
