### ISSUE TITLE
Error while attempting to install PyCrypto on Python 3.6

### ISSUE THREAD

**Issue by zenchiu** [CyberSource/cybersource-rest-client-python#42]
Hi CYBS team,

pycrypto seems not maintained anymore, may I know why you still keep using it? 

'Collecting pycrypto==2.6.1', '  Using cached pycrypto-2.6.1.tar.gz (446 kB)', 'Building wheels for collected packages: pycrypto', '  Building wheel for pycrypto (setup.py): started', "  Building wheel for pycrypto (setup.py): finished with status 'error'", '  Running setup.py clean for pycrypto', 'Failed to build pycrypto', 'Installing collected packages: pycrypto',

Thanks.

**Comment by monu-kumar-visa** [comment]
`PyCrypto` has been removed as a dependency. The latest SDK uses `PyCryptodome`.
