### ISSUE TITLE
Exception when calling PaymentsApi->create_payment: name 'WindowsError' is not defined

### ISSUE THREAD

**Issue by chretienmn** [CyberSource/cybersource-rest-client-python#43]
Needs to be handled for non-windows OS:
https://github.com/CyberSource/cybersource-rest-client-python/blob/f2719b2564785a16a70f52c0d5c41da19825e887/authenticationsdk/core/Authorization.py#L70

**Comment by chretienmn** [comment]
Has this package been tested for production use?

**Comment by gnongsie** [comment]
This has been fixed in version 0.0.17.

@chretienmn Can you confirm and close this issue if you are satisfied with the fix?

**Comment by gnongsie** [comment]
Closing this as the issue has been fixed. Please open a new issue if further doubts exist.
