### ISSUE TITLE
ModuleNotFoundError: No module named 'Crypto'

### ISSUE THREAD

**Issue by Dave-Lopper** [CyberSource/cybersource-rest-client-python#48]
Hello, I'm just getting working on a project using cybersource, and I'm having a dependancy problem : "ModuleNotFoundError: No module named 'Crypto'" Whenever trying to run anything related to the (django) project. 

After some digging, the error occurs on CyberSource/utilities/flex/rsa_verify.py", line 1, and seems to be caused by the case of the import, there is indeed a "crypto" package, when the "Crypto" package is imported;

Thanks guys !

**Comment by jfreres** [comment]
In the libs folder of site-packages rename your crypto package folder to upper case Crypto.

**Comment by strbean** [comment]
https://github.com/CyberSource/cybersource-rest-client-python/pull/73

**Comment by tbrlpld** [comment]
I believe this can be closed as of `0.0.36` release.

**Comment by XLX-forever** [comment]
I am also getting the ModuleNotFoundError: No module named 'Crypto' issue. I have checked that I already installed it using pip3 install pycryptodome and it is in the Scripts folder.

**Comment by jfreres** [comment]
Last I recall the workaround was to lowercase your Crypto folder in the scripts directory ‘crypto’

Justin Freres
Software Engineer IV, IT Business Software Team
AG National Office AG.org<http://ag.org/> | (417) 862-2781 x.4626
***@***.***

**Comment by monu-kumar-visa** [comment]
`crypto` library has been removed as a dependency from version 0.0.36 and onwards.

**Comment by wilsonwambugu** [comment]
ModuleNotFoundError: No module named 'cybersource_rest_client_python

AM GETTING this issue
